# Generated by Django 2.2.7 on 2019-11-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
    ]
