# Generated by Django 2.2.7 on 2019-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20191120_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='idStaff',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
