# Generated by Django 2.2.5 on 2019-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('direction', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('phone2', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
            },
        ),
    ]
