# Generated by Django 2.2.5 on 2019-10-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('ShippingDescription', models.CharField(max_length=100, null=True)),
                ('Store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'verbose_name': 'Arrangement',
                'verbose_name_plural': 'Arrangement',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('direction', models.CharField(max_length=100, null=True)),
                ('phone1', models.CharField(max_length=100, null=True)),
                ('phone2', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='TypeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'TypeOrder',
                'verbose_name_plural': 'TypeOrder',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderData', models.DateField(null=True)),
                ('deliverData', models.DateField(null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('typeOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.TypeOrder')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('arrangement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.Arrangement')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.Client')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.Order')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
    ]
